### ISSUE TITLE
Issue with auto-setup

### ISSUE THREAD

**Issue by mfonolleda** [alkacon/opencms-docker#13]
Hi, 

I have an error when executing "20_check_install.sh". More specifically, when executing line 113 (auto-setup):

``
java -classpath "${OPENCMS_HOME}/WEB-INF/lib/*:${OPENCMS_HOME}/WEB-INF/classes:${TOMCAT_LIB}/*" org.opencms.setup.CmsAutoSetup -path ${CONFIG_FILE}
``
Instead of just creating a new database, the CmsAutoSetup class appears to try to access some tables from the database (which obviously do not exist because it is an install). Because of the error, it is not able to initialize the user driver. Any help on what may be the issue is appreciated.

``
Caused by: java.sql.SQLSyntaxErrorException: Table 'opencms.CMS_GROUPS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.15.jar:8.0.15]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.15.jar:8.0.15]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.15.jar:8.0.15]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970) ~[mysql-connector-java-8.0.15.jar:8.0.15]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020) ~[mysql-connector-java-8.0.15.jar:8.0.15]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-2.7.6.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-2.7.6.jar:?]
        at org.opencms.db.generic.CmsUserDriver.existsGroup(CmsUserDriver.java:763) ~[opencms.jar:11.0.0]
        at org.opencms.db.generic.CmsUserDriver.internalCreateDefaultGroups(CmsUserDriver.java:2217) ~[opencms.jar:11.0.0]
        at org.opencms.db.generic.CmsUserDriver.fillDefaults(CmsUserDriver.java:831) ~[opencms.jar:11.0.0]
        at org.opencms.db.CmsDriverManager.init(CmsDriverManager.java:5168) ~[opencms.jar:11.0.0]
        at org.opencms.db.CmsSecurityManager.init(CmsSecurityManager.java:3431) ~[opencms.jar:11.0.0]
        ... 46 more
``

**Comment by mfonolleda** [comment]
Solved!
